pacman::p_load(tidyverse, estimatr, broom, summarytools, fixest, binsreg)
library(usmap)
library(ggplot2)
library(RColorBrewer)
library(tidyverse)
library(stringr)
library(cdlTools)
library(readxl)
library(gtsummary)
library(ggeffects)

#set wd ("/ecns_560_project")
source("scripts/cleaning.R")
source("scripts/exploratory_analysis.R")
source("scripts/econometric_analysis.R")
